fixtures/base.js
page_objects/documentsPage.js
page_objects/documentsTrashPage.js
page_objects/signPage.js
testData.js
tests/02Autorization.spec.js
tests/base.js
tests/navigation.spec.js

Поскольку для cleanData оказалось несколько блокеров, и коллегам придется пока самостоятельно очищать свою дату, оставила некоторые методы для очистки документов для общего пользования.

loginBusinessUser fixture added

---

.env.example
fixtures/base.js
page_objects/signPage.js
page_objects/templatesActivePage.js
testData.js
tests/06Folders.spec.js

- создание fixtures: Сreate New Folder
- создание TC_06_24_01 Verify the business user can delete folder

TC_06_24_01 | Verify the business user can delete folder

---

page_objects/settingsBillingPage.js
page_objects/settingsBillingPlanPage.js
page_objects/settingsCompanyPage.js
page_objects/signPage.js
testData.js
tests/14Billing.spec.js

1 Created new pages: SettingsCompanyPage, SettingsBillingPage, SettingsBillingPlanPage
2 Added locator and method to SignPage
3 Created TC_14_57_02 test in 14Billing.spec.js

TC_14_57_02 | Billing: Verify the ability to successfully downgrade subscription

---

testData.js
tests/06Folders.spec.js

1. создание папки;
2. после expect - удаление папки из Documents, затем из Trash;
3. возвращение на sign page.

TC_06_22_01: Verify the business user can create folder

---

fixtures/base.js
page_objects/settingEditSignature.js
page_objects/signPage.js
testData.js
tests/navigation.spec.js

Add deleteSignature in the fixture
Add settingEditSignature.js
Make additions in signPage.js and testData.js
Add test 'create signature'
Add test 'create and delete signature'

deleteSignature fixture added

---

page_objects/documentsPage.js
testData.js
tests/06Folders.spec.js

1. Написал тест на изменение названия папки
2.  После ожидаемого результата удалил папку и вышел на главную страницу

TC_06_23_01|Rename folder

---

fixtures/base.js
page_objects/documentsPage.js
page_objects/signPage.js
tests/06Folders.spec.js

delete duplicate methods and locators, rename locator from "getToaster" to "getToast"

refactoring: delete duplicate methods and locators

---

.github/workflows/playwright.yml
apiData.js
fixtures/base.js
testData.js
tests/04SignDocument.spec.js
tests/06Folders.spec.js
tests/14Billing.spec.js
tests/navigation.spec.js

Reverts TheFocusTech/SignaturelyQA#32

Revert "Fixture | Clean documents"

---

.env.example
.github/workflows/playwright.yml
apiData.js
fixtures/base.js
playwright.config.js
testData.js
tests/04SignDocument.spec.js
tests/06Folders.spec.js
tests/navigation.spec.js

add cleanDocuments in fixture 
add .env.example
add apiData.js
change config (Firefox and Webkit projects are commented)
yml was changed

Fixture | clean documents, add .env.example

---

page_objects/createNewSignatureModal.js
page_objects/settingsCompanyPage.js
page_objects/settingsEditSignaturePage.js
testData.js
tests/13SettingsEditSignature.spec.js

commit with merged updated main.
- 13SettingsEditSignature.spec.js was created with TC_13_51_01
- createNewSignatureModal.js was created for 'Create New Signature' modal window
- settingsEditSignaturePage.js was created mostly as duplicate of settingEditSignature.js (new file name is more correct. And if new test TC_13_51_01 will work - old page settingEditSignature.js could be deleted with additional refactoring of settingsEditSignaturePage.js).

TC_13_51_01 | Verify that user can create Signature

---

fixtures/base.js
new_pom/pages/loginPage.js

1. add NewLoginPage class to new_pom
2. refactor loginBusinessUser fixture using new_pom
3. tests (in navigation.spec) that are using this fixture work well

Add NewLoginPage class and rf login fixture

---

fixtures/base.js
helpers/preconditions.js
new_pom/components/sideMenuComponent.js
new_pom/components/sideMenuSettingsComponent.js
new_pom/modalWindows/chooseSignatureOrInitialModal.js
new_pom/modalWindows/createOrEditSignatureOnSettingModal.js
new_pom/modalWindows/editSignatureModal.js
new_pom/modalWindows/prepareForSignatureModal.js
new_pom/pages/settings/settingsCompanyPage.js
new_pom/pages/settings/settingsEditSignaturePage.js
testData.js
tests/03CreateDocument.spec.js

TC_03_07_02 | Verify that the user who uploaded the document and Other Signer can sign it

TC_03_07_02 | Verify that the user who uploaded the document and Other Signer can sign it

---

new_pom/pages/settings/settingsEditSignaturePage.js
tests/13SettingsEditSignature.spec.js

TC_13_51_01 was refactored to new POM

TC_13_51_01  | Verify that user can create Signature

---

new_pom/modalWindows/prepareForSignatureModal.js
tests/03CreateDocument.spec.js

TC_03_07_05 | Verify that user can sign a document themselves with Initial

TC_03_07_05 | Verify that user can sign a document themselves with Initial

---

playwright.config.js

Made these changes due to the error below

Removed trace from artifacts, changed video size to smaller

---

new_pom/components/headerComponent.js
new_pom/components/sideMenuComponent.js
new_pom/pages/loginPage.js
package-lock.json
package.json
playwright.config.js
tests/02Authorization.spec.js
tests/14Billing.spec.js

Remove deprecated import.
Add allure-js-commons dependency.
Change labels for Allure report in TC_02_05_01

Allure changes

---

new_pom/components/fileUploaderComponent.js
new_pom/components/sideMenuComponent.js
new_pom/components/toastComponent.js
new_pom/modalWindows/createSignatureOrInitialModal.js
new_pom/modalWindows/prepareForSignatureModal.js
new_pom/modalWindows/successModal.js
new_pom/pages/finalStepPage.js
new_pom/pages/sign/signPage.js
new_pom/pages/sign/uploadFileOnSignPage.js
tests/03CreateDocument.spec.js

TC_03_07_06 | Verify user can create, sign, and send a document to another signer

TC_03_07_06 in allure

---

helpers/preconditions.js
new_pom/components/sideMenuDocumentsComponent.js
new_pom/components/sideMenuSettingsComponent.js
new_pom/modalWindows/chooseSignatureOrInitialModal.js
new_pom/modalWindows/createOrEditSignatureOnSettingModal.js
new_pom/pages/settings/settingsEditSignaturePage.js
tests/04SignDocument.spec.js

TC_04_10_02 | Verify that the user who uploaded the document and other signer can sign it

TC_04_10_02 | Verify that the user who uploaded the document and other signer can sign it

---

helpers/preconditions.js
new_pom/modalWindows/prepareForSignatureModal.js
tests/03CreateDocument.spec.js
tests/04SignDocument.spec.js
tests/07Templates.spec.js
tests/08Forms.spec.js

Replacing doCanvasClicks() with clickDocumentBody()
Added a link to Qase

 Replacing doCanvasClicks() with clickDocumentBody()

---

helpers/preconditions.js
new_pom/pages/templates/createNewTemplatePage.js
tests/05DocumentsTyped.spec.js
tests/07Templates.spec.js

Import CreateTemplateComponent to createNewTemplatePage
Remove methods from CreateNewTemplatePage
change path to method in Precondition
Cosmetic fix in 05DocumentsTyped.spec.js

TC_07_31_01_RF

---

new_pom/modalWindows/createAPIKeyModal.js
new_pom/pages/settings/settingsAPIPage.js
playwright.config.js
tests/12APIkey.spec.js

config: permissions added to verify copying to the clipboard on CI 
SettingsAPIPage: method for simulating the paste action by pressing Ctrl-V Keyboard Shortcuts

RF: TC 12_48_01 Allure

---

fixtures/base.js
helpers/preconditions.js
new_pom/components/sideMenuComponent.js
new_pom/components/tableComponent.js
new_pom/modalWindows/prepareForSignatureModal.js
testData.js
tests/01Registration.spec.js
tests/02Authorization.spec.js
tests/03CreateDocument.spec.js
tests/04SignDocument.spec.js
tests/05DocumentsTyped.spec.js
tests/06Folders.spec.js
tests/07Templates.spec.js
tests/08Forms.spec.js
tests/09Team.spec.js
tests/11Profile.spec.js
tests/12APIkey.spec.js
tests/14SettingsBilling.spec.js
tests/gmailMethods.spec.js

REFACTOR: fields menu locators, options method, allure link, fixture

REFACTOR: fields menu, options, allure link, fixture

---

new_pom/components/tableComponent.js
testData.js
tests/04SignDocument.spec.js
tests/08Forms.spec.js

test TC_08_36_01 added
- TableComponent: locators and methods clickDisableFormBtn(), clickEnableFormBtn()
- testData added

TC_08_36_01 | User can disable and enable a form

---

fixtures/base.js
helpers/preconditions.js
new_pom/components/sideMenuDocumentsComponent.js
new_pom/components/tableComponent.js
new_pom/modalWindows/shareThisDocumentModal.js
testData.js
tests/05DocumentsTyped.spec.js

!!В тесте 2 проверки:
1. Document sent to the email.  - написан
2. Document received by email. - не написан, надо будет потом написать.
Все ранние комментарии были учтены + добавлен Allure.

рефакторинг, добавление allure

---

new_pom/modalWindows/createSignatureOrInitialModal.js
new_pom/modalWindows/prepareForSignatureModal.js
new_pom/pages/finalStepPage.js
tests/03CreateDocument.spec.js

TC_03_07_01 | Sign a document - verify that user can sign a document themselves +  Add allure
fix mistake in discribe

TC_03_07_01 | Sign a document - verify that user can sign a document themselves Add allure

---

new_pom/modalWindows/downgradeToPersonalPlanModal.js
new_pom/pages/settings/settingsBillingPlanPage.js
tests/14SettingsBilling.spec.js

TC_14_57_02 add allure

---

fixtures/base.js
helpers/preconditions.js
new_pom/components/tableComponent.js
new_pom/modalWindows/confirmTrashEmptyingModal.js
new_pom/modalWindows/deleteModal.js
new_pom/pages/documents/documentsTrashPage.js
playwright.config.js
testData.js
tests/05DocumentsTyped.spec.js

TC_05_19_01 | Verify that deleted document has been moved to the trash by using ACTIONS_options dropdown menu and then deleted permanently

---

tests/03CreateDocument.spec.js

TC_03_07_04 | Verify that user can sign a document themselves with existed signature

---

tests/12APIkey.spec.js

Allure notation added to test TC_12_48_02

RF TC_12_48_02 | Add Allure

---

tests/04SignDocument.spec.js

TC_04_10_03 | Verify that the user who uploaded the document can send it to signer

TC_04_10_03 | Verify that the user who uploaded the document can send it to signer

---

tests/13SettingsEditSignature.spec.js

Add correct link to allure ATC_13_52_01

RF TC_13_52_01 | Verify that user can edit Signature.

---

fixtures/base.js
new_pom/pages/signUp/signUpBusinessPage.js
testData.js
tests/01Registration.spec.js

TC_01_59_01 | Verify successful registration of Business user (parameterized test)

---

tests/11Profile.spec.js

RF_TC_11_46_03 | Verify user can enabling, disabling checkboxes

---

helpers/preconditions.js
new_pom/components/tableComponent.js
new_pom/modalWindows/prepareForSignatureModal.js
new_pom/pages/settings/settingsProfilePage.js
tests/03CreateDocument.spec.js
tests/05DocumentsTyped.spec.js
tests/06Folders.spec.js
tests/08Forms.spec.js
tests/11Profile.spec.js

refactor some methods
